# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_move', models.CharField(default='add', max_length=6)),
                ('status', models.IntegerField(default=1)),
                ('title', models.CharField(default='Untitled', max_length=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=45)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_words', to='type_type.User')),
                ('deleter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_words', to='type_type.User')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_words', to='type_type.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updater', to='type_type.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='writer1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w1_projects', to='type_type.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='writer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w2_projects', to='type_type.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='writer_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_turn', to='type_type.User'),
        ),
        migrations.AddField(
            model_name='invite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviting_user', to='type_type.User'),
        ),
        migrations.AddField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to='type_type.User'),
        ),
    ]
