# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to='type_type.User'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviting_user', to='type_type.User'),
        ),
    ]
