# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_type', '0002_auto_20180301_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater', to='type_type.User'),
        ),
    ]
