# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-01 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_type', '0003_auto_20180301_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='deleter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_words', to='type_type.User'),
        ),
    ]
